apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- $drink := first .Values.favorite.drinks }}
  {{- $map := dict "drink" $drink "name" $.Release.Name }}
  {{- include "loop-tpl.mytemplate" $map | nindent 2 }}
  {{- /* include allows only a valiable */ -}}
  {{- $drinks := rest .Values.favorite.drinks }}
  {{- range $drink := $drinks }}
  {{- $map := dict "drink" $drink "name" $.Release.Name }}
  {{- include "loop-tpl.mytemplate" $map | nindent 2 }}
  {{- end }}
